# Generated by Django 6.0.2 on 2026-02-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=21)),
                ('lastname', models.CharField(max_length=21)),
                ('age', models.IntegerField()),
                ('course', models.CharField()),
            ],
        ),
    ]
